### PR TITLE
Fix timezone parsing in DateTimeParser with Java 6

### LINKED ISSUE #181: SimpleDateFormat doesn't support timezone parsing with the character X in the pattern string
I downloaded latest code and it build successfully. But when I try to connect to EWS, I still got error:

Jan 20, 2015 2:17:58 PM org.apache.http.impl.auth.HttpAuthenticator generateAuthResponse
WARNING: NEGOTIATE authentication error: Invalid name provided (Mechanism level: Could not load configuration file C:\WINDOWS\krb5.ini (The system cannot find the file specified))
Exception in thread "main" microsoft.exchange.webservices.data.ServiceRequestException: The request failed. The request failed. The remote server returned an error: (401)Unauthorized

The code I am using is from "Download ZIP". I have httpclient-4.3.5, httpcore-4.3.3 in build path. And here is my client code: 
ExchangeService service = new ExchangeService(); 
		ExchangeCredentials credentials = new WebCredentials("username", "password", "myDomain"); 
		service.setCredentials(credentials);
		service.setUrl(new URI("https://ewsURL"));  
		ItemView view = new ItemView(5);  
		FindItemsResults<Item> findResults = service.findItems(WellKnownFolderName.Inbox, view);	

Could anyone give some suggestion? I really appreciate it! Thanks a lot in advance!

### PR DESCRIPTION
**Pull request by evpaassen**
I have included joda-time as a dependency. It may seem overkill for fixing this issue, but if we do include it now we're able to use it on other places in the future.

Fixes #181.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@evpaassen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by ahaarrestad** [comment]
Can you make sure that the "simple" one used by recurring appointments still handles the different timestamp formats?

**Comment by evpaassen** [comment]
> Can you make sure that the "simple" one used by recurring appointments still handles the different timestamp formats?

The existing test cases cover this, right? These tests succeed.

**Comment by ahaarrestad** [comment]
hopefully they cover it....

**Comment by evpaassen** [comment]
Well these tests are not exactly rock science. The `testDateOnlyWithTimeZone*()` methods test the parsing of recurrence dates with timezone offsets:

https://github.com/eveoh/ews-java-api/blob/fix-datetimeparser-java6/src/test/java/microsoft/exchange/webservices/data/util/DateTimeParserTest.java

**Comment by MikeN123** [comment]
I believe this fixes #44

**Comment by vboctor** [comment]
Thanks @evpaassen - merged.

**Pull request merged**
