### PR TITLE
Java Double type can't be used for the 'PercentComplete' element in Task

### PR DESCRIPTION
**Pull request by vbauer**
I think it should help.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vbauer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
@vbauer plz update your pr :trollface:

**Comment by vbauer** [comment]
@serious6 Done.

**Comment by serious6** [comment]
@vbauer thanks for your contribution

**Pull request merged**
