### PR TITLE
Fix for Issue #17

### PR DESCRIPTION
**Pull request by avromf**

### CODE REVIEW

**Comment by serious6** [comment]
@avromf please [update your branch](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/) so this PR can be merged. I would also suggest some unittests to be added.

**Comment by avromf** [comment]
Ok, I believe it is now updated.

**Comment by serious6** [comment]
thanks. Once you added the suggested tests this will be merged.

**Comment by vboctor** [comment]
Thanks @avromf for your contribution.

**Pull request merged**
