### PR TITLE
Added more date-patterns and a test to resolve the milliseconds issue

### PR DESCRIPTION
**Pull request by ahaarrestad**
Even though the example in #206 is a bit special (max-date?) the pattern can be supported. Added datePattern and a test.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahaarrestad__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vboctor** [comment]
+1

**Comment by evpaassen** [comment]
Fix is looking good, but could you please include 'Fixes OfficeDev/ews-java-api#206` in your commit message? Then the commit would be linked to the issue and it will auto-close the issue when the commit is merged into master.

**Comment by ahaarrestad** [comment]
added comment and squashed commits

**Pull request merged**
