### PR TITLE
mvn autodeployment

### PR DESCRIPTION
**Pull request by serious6**
- added secure vars

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@serious6__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vboctor** [comment]
:+1:

**Comment by serious6** [comment]
little bad that this can only be tested in production

**Comment by vboctor** [comment]
It is for security reasons.  They don't want secure variables available to pull requests.  But I agree, would be nice to enable pull request processing when it is submitted by a repository owner for example.

**Comment by vboctor** [comment]
I wonder if after a while, we will know which secure value is what.  Should we add a comment next to each one about its purpose?

**Comment by serious6** [comment]
@vboctor maybe this will make attacks easier since for normal users this might not be a relevant information. This might also be the reason why travis also encrypts the secure-variables name rather then leaving it in plain text. For the issue dealing with gpg signed artifacts I made some local tests with my keybase secret which worked quite well. I therefore have send you an invitation to keybase since it´s looking quiet interesting in the order of having a central spot where users may validate files against.
So if you like give it a try. For my local test I followed these steps:
-  accept invitation and add basic information to [keybase.io](https://keybase.io) account
-  download / install keybase for cmd
  -  **windows:**
    -  download / install [gnupg](https://www.gnupg.org/download/)
    - (gnupg didnt create a temp folder on my system. maybe you will have to create it manually) -> *C:\ Users\<User>\.gnupg*
    -  download / install [node.js](https://nodejs.org/#download)
  -  **linux**
    -  `apt-get install gnupg`
    - `apt-get install nodejs-legacy npm`
  -  `npm install -g keybase-installer`
  -  `keybase-installer`
  -  `keybase version` 

nearly finished now import keys to the keyring:
- `keybase login`
- `gpg --list-keys` (you should now see the keybase key in your keyring)

finished. now test with maven:
* navigate to ews-java-api via cmd
* `mvn clean install -Dgpg.passphrase=MYKEYBASESECRETKEY`

**Pull request merged**
