### PR TITLE
fix the Project hierarchie issue #39

### PR DESCRIPTION
**Pull request by serious6**
I am currently adding commits here. While I am doing so you can see the result so maybe we can find problems earlier.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@serious6__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
*package attributes is ready to roll*

**Comment by serious6** [comment]
*package autodiscover (subpackages follow) is ready to roll*

**Comment by vboctor** [comment]
@serious6 I think we should have auto-discover a separate library all together.  The reason is that auto-discover can be shared between the Exchange Web Services (SOAP) and the Exchange REST APIs.  Just something to take into consideration.  We can of course do this in steps.

So application can just take a dependency on auto-discover to discover the end point then using REST, or do auto-discover and then use ews-java-api to connect to SOAP service.

**Comment by serious6** [comment]
@vboctor ok are you fine when we will do this as an extra task or pr? The reason why I think this could be usefull is that this refactoring will be huge even without side effects.

**Comment by serious6** [comment]
*package autodiscover completed*

**Comment by vboctor** [comment]
@serious6 makes sense to have it as another step.  I just wanted to mention it to make sure that we take this into consideration as we are crafting the package.

**Comment by serious6** [comment]
*package dns / credentials completed*

**Comment by serious6** [comment]
*package enumerations completed*

**Comment by serious6** [comment]
*package exceptions completed*

**Comment by serious6** [comment]
*package properties completed*

**Comment by serious6** [comment]
*package interfaces completed*

**Comment by serious6** [comment]
*package search completed*

**Comment by serious6** [comment]
*package sync completed*

**Comment by serious6** [comment]
*package unifiedMessaging completed*

**Comment by serious6** [comment]
*package notifications completed*

**Comment by serious6** [comment]
*package misc completed*

**Comment by serious6** [comment]
*package security completed*

**Comment by serious6** [comment]
ok I think this is it. I will also move the tests into their desired folders tomorrow

**Comment by serious6** [comment]
your comments on the change are welcome

**Comment by serious6** [comment]
test classes have now also been moved

**Comment by vboctor** [comment]
:+1: Thanks for doing this work.

I think it is unfortunate that we can have such organization while not exposing more internals of the implementation as public though.

In the C# world, I can organize code using namespaces and folder hierarchy, while only exposing the small number of methods / types that I need externally.  This also helps user to easily discover the classes that they are expected to use without being buried into a set of internally targeted classes / methods.

**Comment by serious6** [comment]
Since we only have public, private, protected and package private here I think this is some kind of given by the project architecture. There might be a twist but we have to decide if we want stuff as to be just in one package or have it splitted for better understanding.

**Comment by vbauer** [comment]
You did the really great work! I just want to add some thoughts about this changes (maybe it will be interesting for you):

1. Package is similar to a database table. A database relation should be named in the singular as its records are considered to be instances of the relation. I prefer to make name of packages in singular.
2. Another moment with packages: using of camel-case for naming (ex: configurationSettings, idConversion, timeZones). Maybe it will be better to use just a simple names (like "configuration" or "setting").
3. Package "autodiscover": maybe it will be better to move all error-classes, collection-classes into separate packages. 
4. Package "definition": it will be great to add package "primitive" for definitions like BoolPropertyDefinition, DoublePropertyDefinition, ByteArrayPropertyDefinition, etc..
5. We can simplify all package, if we add "base" sub-packages for abstract classes.
6. Maybe it will be useful to add some extra sub-packages for "interfaces" (ex: "delegate" for delegate-classes, "base" for IFunction, IPredicate, etc..)

**Comment by serious6** [comment]
@vbauer thanks for the feedback. I think the mentioned point 1 may be depending on the personal style but I will be looking forward in having these things integrated. If you like feel free to add a PR on this one.

**Comment by evpaassen** [comment]
I did not find time this review this yet, but I'd like to comment on the above.

> * Package is similar to a database table. A database relation should be named in the singular as its records are considered to be instances of the relation. I prefer to make name of packages in singular.

Here's the explanation: http://programmers.stackexchange.com/questions/75919/should-package-names-be-singular-or-plural

> * Another moment with packages: using of camel-case for naming (ex: configurationSettings, idConversion, timeZones). Maybe it will be better to use just a simple names (like "configuration" or "setting").

Camel-casing in package names is very uncommon indeed. Package names should be lower case, no dashes, no underscores.

> * We can simplify all packages, if we add "base" sub-packages for abstract classes.
> * Maybe it will be useful to add some extra sub-packages for "interfaces" (ex: "delegate" for delegate-classes, "base" for IFunction, IPredicate, etc..)

I don't see a real advantage of this. I'm also not aware of any other major Java project using such package organisation.

**Comment by vbauer** [comment]
> Here's the explanation: http://programmers.stackexchange.com/questions/75919/should-package-names-be-singular-or-plural
Indeed.

> Camel-casing in package names is very uncommon indeed. Package names should be lower case, no dashes, no underscores.
Maybe I was unclear, but it was a point: to prevent using camel-case in package naming.

> I don't see a real advantage of this. I'm also not aware of any other major Java project using such package organisation.
Ex: joda-time. Yes, I agree that it is not very popular practice for existing Java projects, because most of them were designed a long time ago. They were very small/compact in the beginning of their life-cycle and after some time it was impossible to re-structure packages without breaking of backward compatibility. The idea of this way is the same: to minimize classes in packages using groups to prevent huge number of classes (and refactoring) in the future. Also it simplifies navigation, because classes are grouped by meaning (ofc). Maybe it is not necessary for now.

**Comment by serious6** [comment]
Despite the mentioned stackoverflow post I looked around a little and bigger apis often use singular names. And I must say I feel much better with that. It might also be a not so simple question if all the files in the package are homogeneous or heterogeneous. And using singular names might also be more stable for later changes. The only thing I could not rename by now is interfaces since interface is a reserved name.

**Comment by serious6** [comment]
@vboctor I also moved all autodiscover corresponding files to that package for later extraction

**Comment by serious6** [comment]
@vbauer , @evpaassen maybe you can have a brief look at the package organisation? Maybe you also have a suggestion for dealing with the interfaces package (I am currently not that creative)?

**Comment by serious6** [comment]
maybe we can also discuss if this should be merged with all the containing commits or if this should be squashed?

**Comment by vbauer** [comment]
@serious6 I suggest to glue (squash) all commits. I'm not sure that it is important to show full history for developers.

Maybe it will be simpler to stop at the suggested organization of packages. If I understand correctly, the first official release will not be in the nearest future, so we can improve it later.

**Comment by evpaassen** [comment]
> @vbauer , @evpaassen maybe you can have a brief look at the package organisation and also have a suggestion for dealing with the interfaces package (I am currently not that creative)?

I'll try to find some time soon.

> maybe we can also discuss if this should be merged with all the containing commits or if this should be squashed? Even though this might heavily increase the commit counts I would suggest in merge every commit for later documentation.

> @serious6 I suggest to glue (squash) all commits. I'm not sure that it is important to show full history for developers.

No, please don't squash. With one large commit, there's a high chance the rename tracking in git will be detecting renames incorrectly, due to certain similarity in some simple files. I don't see why a higher commit count would be a problem, as this **won't** make navigation through the revision tree harder when blaming.

**Comment by vbauer** [comment]
> No, please don't squash. With one large commit, there's a high chance the rename tracking in git will be detecting renames incorrectly, due to certain similarity in some simple files. (Yes, I found this out the hard way...)

Never ever saw described situation. As I understand André did not rename files (only folders), so it should be fine. Anyway, it could be checked (squashing commits + folder comparison).

> I don't see why a higher commit count would be a problem, as this won't make navigation through the revision tree harder when blaming.

It is not for blaming, but to keep history clean. At the current moment there are 90 commits, so it will just complicate navigation.

**Comment by serious6** [comment]
> Maybe it will be simpler to stop at the suggested organization of packages. If I understand correctly, the first official release will not be in the nearest future, so we can improve it later.

As inteded by [semantic versioning](http://semver.org) the next changes that will break compatibility will be in version `3.0`. If you guys dont mention any further changes and @vboctor also gives his go I think we can have this for now. 
In my opinion there are some goals that can be fixed later on:
* interfaces should not be placed in a seperated package [stack](http://stackoverflow.com/questions/1004980/should-interfaces-be-placed-in-a-separate-package)
* enumeration package should be more structured or this should also be moved to the main packages where they are used
* exception package should be more structured or this should also be moved to the main packages where they are used see package autodiscover for example

**Comment by serious6** [comment]
@vbauer I think the main goal of having these commits integrated 'as is' would be to follow the changes that have been taken place. Once we will squash the single steps will be lost forever.

**Comment by vboctor** [comment]
- I'm assuming for Java gurus this is an overall good change.  I mentioned my issues with it compared to C#.  More stuff becoming public.
- :+1: for not squashing changes
- :+1: for getting this in and we can iterate later, but ideally before v2 is out.
- :+1: for grouping interfaces/enumerations/exceptions where they logically belong vs. in a package on their own.

**Comment by vbauer** [comment]
@serious6 Yes, agree. It makes sense, if it is really needed.

**Comment by vbauer** [comment]
@serious6 Just wanted to say thank you again, great work!

**Comment by serious6** [comment]
np. Also thanks for discussion.

**Comment by nickersd** [comment]
Using the syntax that is in the documentation I suddenly started getting
the below.  I would post my code but it's a cut and paste from the readme.

microsoft.exchange.webservices.data.autodiscover.exception.AutodiscoverLocalException:
The Autodiscover service couldn't be located.
at
microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.internalGetLegacyUserSettings(AutodiscoverService.java:743)
at
microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getLegacyUserSettings(AutodiscoverService.java:520)
at
microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.internalGetLegacyUserSettings(AutodiscoverService.java:967)
at
microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1856)
at
microsoft.exchange.webservices.data.core.ExchangeService.getAutodiscoverUrl(ExchangeService.java:3672)
at
microsoft.exchange.webservices.data.core.ExchangeService.autodiscoverUrl(ExchangeService.java:3631)

**Comment by evpaassen** [comment]
Could that be related to #270 (with PR #271)?

**Comment by GouthamPatala** [comment]
I guess PR #271 might solve this. @nickersd, can you please try your code by pulling the code from https://github.com/GouthamPatala/ews-java-api, build the jar and replace the current ews jar you got with this newly built jar in the classpath.

**Pull request merged**
