### PR TITLE
Ewsxmlreaderfix

### PR DESCRIPTION
**Pull request by atamer**
I got the following exception when the subject of one email subject is : =?iso-8859-1?Q?=00?=
and empty appointments got the same error, I think it is also a solution to #262 

```
microsoft.exchange.webservices.data.EWSHttpException: Connection not established
     at microsoft.exchange.webservices.data.HttpClientWebRequest.throwIfConnIsNull(Unknown Source)
     at microsoft.exchange.webservices.data.HttpClientWebRequest.getResponseHeaders(Unknown Source)
     at microsoft.exchange.webservices.data.ExchangeServiceBase.processHttpResponseHeaders(Unknown Source)
     at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(Unknown Source)
     at microsoft.exchange.webservices.data.MultiResponseServiceRequest.execute(Unknown Source)
     at microsoft.exchange.webservices.data.ExchangeService.findItems(Unknown Source)
     at microsoft.exchange.webservices.data.ExchangeService.findItems(Unknown Source)
```

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@atamer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
@atamer looks ok. Please squash the two commits to a single one and also add some unit-tests for the parsing process.

**Comment by serious6** [comment]
@atamer are you planing any changes here?

**Comment by vboctor** [comment]
I'm unable to see the exact fix in the code.  There is a lot of styling changes in this change.  Let's make sure that we have a targeted fix.

Are we saying that "data" within an object can break our xml parser?  I would like the library to break when the envelope XML returned by the service is broken.  However, it shouldn't break if the data has complete non-sense.  Are we doing the right escaping?

**Comment by serious6** [comment]
@atamer plz remove the unecessary commits. If you dont I will create another PR of this. With only the small change left.

**Comment by serious6** [comment]
Thanks @atamer opened #364 with only the significant contribution.

**Pull request closed without merging**
