### PR TITLE
First suggested solution to issue 23. The data does not seem to contain ...

### PR DESCRIPTION
**Pull request by ahaarrestad**
suggested solution to https://github.com/OfficeDev/ews-java-api/issues/23

Trying to return some usable information for the errormessage. Some info is better than none. Anybody got suggestions for improvements / more tests needed?

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahaarrestad__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by MikeN123** [comment]
Imho we should just drop the whole function, it does not belong in the library, and we already have a `Class.getSimpleName()` if you want to know the name.

**Comment by serious6** [comment]
+1 for deletion as mentioned in #23

**Comment by ahaarrestad** [comment]
I will delete and simplify :-)

**Comment by serious6** [comment]
@ahaarrestad please  squash the two commits down into a single one.

**Comment by ahaarrestad** [comment]
suqashed commits and improved commit-message

**Comment by serious6** [comment]
maybe this is a more simple candidate for having some tests added?

**Comment by serious6** [comment]
@ahaarrestad thanks for the contribution.

**Pull request merged**
