### PR TITLE
Remove unstable part in Readme

### PR DESCRIPTION
**Pull request by WtfJoke**
Remove part of readme, that indicates, there isnt any stable version out yet.

Since, there is a version 2.0 out, there isnt any need for this information.

### CODE REVIEW

**Comment by serious6** [comment]
Maybe we should just link to the wiki pages and update the info there?

**Comment by WtfJoke** [comment]
Makes sense. I'll update the pr this noon.
I'll also fix the entry in the wiki, because there is the same wrong text as well.

**Comment by WtfJoke** [comment]
@serious6 I'll updated the readme to the link. 

There are some duplicate informations on the wiki.
For example the maven/gradle part can be either found here:
https://github.com/OfficeDev/ews-java-api/wiki#maven--gradle-integration
or here:
https://github.com/OfficeDev/ews-java-api/wiki/Getting-Started-Guide#maven--gradle-integration

Shouldnt we delete informations on the first page? So we dont need to update two pages.

**Comment by serious6** [comment]
Thanks for pointing this out. The information should be centralized while updating the remaining references. Maybe the sections on the readme should also be more generalized/combined while pointing to the wiki pages.

**Comment by serious6** [comment]
@WtfJoke thanks for your contribution

**Pull request merged**
