### PR TITLE
Fix #216: Remove invalid license.

### LINKED ISSUE #216: project contains two, inconsistent licenses
Which license is valid for the project?

1) OfficeDev/ews-java-api/license.txt
2) OfficeDev/ews-java-api/src/site/resources/License.docx

Please remove the unnecessary one.

### PR DESCRIPTION
**Pull request by vboctor**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vboctor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
@vboctor can you describe what you changed in `src/site/resources/License.docx` as I dont see a difference here.

**Comment by serious6** [comment]
the heading is also saying `MICROSOFT SOFTWARE LICENSE TERMS
[...] JAVA 1.2` maybe this should be formed to a more general heading, to not have this fixed with every version of ews-java-api?

**Comment by vboctor** [comment]
@serious6 I've deleted the docx file since it is redundant.  The official license is license.txt.

Will check the header you are referring to.

**Comment by serious6** [comment]
@vboctor please sign the cla ;-)

**Pull request merged**
