### PR TITLE
Clear text body

### PR DESCRIPTION
**Pull request by nickersd**
Reference:  #404 how to get the text values of appointment.getBody() without HTML Tags?

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nickersd__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
I think exchange already offers to get the plain-text. See this [post](http://stackoverflow.com/a/11246458) for more information.

**Comment by serious6** [comment]
@nickersd any feedback if the suggested example resolves your situation?

**Comment by nickersd** [comment]
I had no situation.  I was using jsoup before and was just looking to contribute. This pull can be ignored.

**Pull request closed without merging**
