### PR TITLE
Refactor enumerations

### PR DESCRIPTION
**Pull request by serious6**
Hi there,
second attempt for a new package structure at the enumerations level. All enumerations related to autodiscover have been moved there. Additionally other enumerations are moved to `core -> enumeration -> XXXX`. Splitted enumerations to several subpackages:
* attribute
* availability
* dns
* misc
* notification
* permission
* property
* search
* service
* sync

Any feedback or suggestions are welcome.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@serious6__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
_related to #39_

**Comment by vboctor** [comment]
:+1:  - did we based this re-structuring on ews-managed-api or did you come up with the split?

**Comment by serious6** [comment]
@vboctor this is some kind of split with ews-managed-api since all enumerations are stored in the enumerations package there. Nevertheless I think this PR provides a more fitting aproach due to the already refactored Interfaces and Exceptions that also make a split from ews-managed-api.

**Comment by serious6** [comment]
@vboctor are you fine with this changes?

**Comment by vboctor** [comment]
yes

**Pull request merged**
