### PR TITLE
Fix bug. EmailAddress.tostring() is incorrect 

### PR DESCRIPTION
**Pull request by icezmb**
The logic of EmailAddress.tostring() is incorrect, fix it

### CODE REVIEW

**Comment by serious6** [comment]
@icezmb once you iterated the suggestions and sign the [cla](https://cla.azure.com) this can be merged.

**Comment by azurecla** [comment]
__@icezmb__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by icezmb** [comment]
@serious6 , I have signed the cla. Thanks

**Comment by serious6** [comment]
@icezmb so only the tests are missing ;-)

**Comment by vboctor** [comment]
@icezmb thanks for your contribution.  It would be great if you can follow up at one point with the other tests requested here.

**Pull request merged**
