### PR TITLE
sign artifact with gpg

### PR DESCRIPTION
**Pull request by serious6**
- sign all artifacts for deployment with gpg
- artifacts will only be sign if -Dparameter with passphrase is set

The following will **not** track gpg signature process (this will allow every user to make local builds):
```xml
   mvn clean install
   mvn clean deploy
```

The following will track gpg signature process:
```xml
   mvn clean install -Dgpg.passphrase=myverysupersecretpassphrase
   mvn clean deploy -Dgpg.passphrase=myverysupersecretpassphrase
```

* [tutorial on gpg](http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/#.VP9VPvmG-3g)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@serious6__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vbauer** [comment]
Maybe it will be also useful to update README and add information about this feature?

**Comment by serious6** [comment]
yes. I will add this to the wiki.

**Comment by vbauer** [comment]
Thank you.

**Comment by serious6** [comment]
@vbauer I added a [wiki-page](https://github.com/OfficeDev/ews-java-api/wiki/Building-EWS-JAVA-API) for building the api

**Comment by vbauer** [comment]
@serious6 Thank you!

**Pull request merged**
