### PR TITLE
TimeWindow.writeToXmlUnscopedDatesOnly should have UTC set on formatter

### LINKED ISSUE #241: Availability Service timewindow shifted by timezone
The `getUserAvailability()` api is not returning the expected results/events.
It seems that the timewindow argument is mis-interrepted as UTC instead of my local timezone.

For this test I have 4 meeting events configured for user ps5502 (using EST) as follows:

Event1: March 4th 19:00 to 20:00
Event2: March 5th 10:00 to 11:00
Event3: March 5th 14:00 to 17:00
Event4: March 5th 19:00 to 19:30

I'm testing against a 2010 exchange server and you can see from this test code output
that I'm getting back **events 1, 2, 3** where I should be getting **events 2, 3, 4**
for the specified time window (which is from the start of today to the start of tomorrow - 24hrs).

```
2015-03-05 18:50:09,490 [main] jvh.ewsClient.EWSClient INFO - buildStartEndTime() start Thu Mar 05 00:00:00 EST 2015 end Fri Mar 06 00:00:00 EST 2015
2015-03-05 18:50:10,099 [main] jvh.ewsClient.EWSClient INFO - getAvailability() start Thu Mar 05 00:00:00 EST 2015 end Fri Mar 06 00:00:00 EST 2015
2015-03-05 18:50:10,099 [main] jvh.ewsClient.EWSClient INFO - getAvailability() results for ps5502@ca.avaya.com events: 3
2015-03-05 18:50:10,099 [main] jvh.ewsClient.EWSClient INFO - getAvailability()    event 1 start: Wed Mar 04 19:00:00 EST 2015 end: Wed Mar 04 20:00:00 EST 2015
2015-03-05 18:50:10,100 [main] jvh.ewsClient.EWSClient INFO - getAvailability()    event 2 start: Thu Mar 05 10:00:00 EST 2015 end: Thu Mar 05 11:00:00 EST 2015
2015-03-05 18:50:10,100 [main] jvh.ewsClient.EWSClient INFO - getAvailability()    event 3 start: Thu Mar 05 14:00:00 EST 2015 end: Thu Mar 05 17:00:00 EST 2015
```

Test code as follows:

    private TimeWindow buildStartEndTime()
    {
       final Calendar cal = Calendar.getInstance();
       cal.set(Calendar.HOUR_OF_DAY, cal.getActualMinimum(Calendar.HOUR_OF_DAY));
       cal.set(Calendar.MINUTE, cal.getActualMinimum(Calendar.MINUTE));
       cal.set(Calendar.SECOND, cal.getActualMinimum(Calendar.SECOND));
       cal.set(Calendar.MILLISECOND, cal.getActualMinimum(Calendar.MILLISECOND));
       final Date start = cal.getTime();
       cal.add(Calendar.DATE, 1);
       final Date end = cal.getTime();
 
       LOG.info("buildStartEndTime() start " + start + " end " + end);
       return new TimeWindow(start, end);
    }
    
    private void testAvailabilityService()
    {
       final List<String> attendeeList = Arrays.asList("ps5502@ca.avaya.com");
       final TimeWindow tw = buildStartEndTime();
       getAvailability(attendeeList, tw);
    }
    
    private void getAvailability(List<String> attendeeList, final TimeWindow tw)
    {
       final List<AttendeeInfo> attendees = new ArrayList<AttendeeInfo>();
       for (final String attendee : attendeeList)
       {
          attendees.add(new AttendeeInfo(attendee));
       }
 
       try
       {
          GetUserAvailabilityResults results = service.getUserAvailability(attendees, tw, AvailabilityData.FreeBusyAndSuggestions);
 
          LOG.info("getAvailability() start " + tw.getStartTime() + " end " + tw.getEndTime());
          int userIndex = 0;
          for (AttendeeAvailability attendeeAvailability : results.getAttendeesAvailability())
          {
             if (attendeeAvailability.getErrorCode() == ServiceError.NoError)
             {
                LOG.info("getAvailability() results for " + attendees.get(userIndex).getSmtpAddress() + " events: " + attendeeAvailability.getCalendarEvents().size());
 
                // loop thru the rec'd events
                int eventCount = 1;
                for (CalendarEvent calEvent : attendeeAvailability.getCalendarEvents())
                {
                   LOG.info("getAvailability()    event " + eventCount + " start: " + calEvent.getStartTime() + " end: " + calEvent.getEndTime());  // + " " + " details: " + calEvent.getDetails() + " subject: " + (calEvent.getDetails() == null ? "null" : calEvent.getDetails().getSubject()));
                   eventCount++;
                }
             }
             else
             {
                LOG.info("getAvailability() error for " + attendees.get(userIndex).getSmtpAddress() + ": "+ attendeeAvailability.getErrorCode());
             }
             userIndex++;
          }
       }
       catch (Exception e)
       {
          LOG.error("getAvailability() failed", e);
       }
    }

BTW... I executed this same test with the older version 1.1.5 and it does the same thing.
However, the old version sends back calendar events in UTC where the lastest 2.0 code
sends the events back in my local timezone (ie: EST).  (which is better :-) )

Test results using the 1.1.5 version:

```
2015-03-05 19:16:07,743 [main] jvh.ewsClient.EWSClient INFO - buildStartEndTime() start Thu Mar 05 00:00:00 EST 2015 end Fri Mar 06 00:00:00 EST 2015
2015-03-05 19:16:09,568 [main] jvh.ewsClient.EWSClient INFO - getAvailability() start Thu Mar 05 00:00:00 EST 2015 end Fri Mar 06 00:00:00 EST 2015
2015-03-05 19:16:09,568 [main] jvh.ewsClient.EWSClient INFO - getAvailability() results for ps5502@ca.avaya.com events: 3
2015-03-05 19:16:09,568 [main] jvh.ewsClient.EWSClient INFO - getAvailability()    event 1 start: Thu Mar 05 00:00:00 EST 2015 end: Thu Mar 05 01:00:00 EST 2015
2015-03-05 19:16:09,569 [main] jvh.ewsClient.EWSClient INFO - getAvailability()    event 2 start: Thu Mar 05 15:00:00 EST 2015 end: Thu Mar 05 16:00:00 EST 2015
2015-03-05 19:16:09,570 [main] jvh.ewsClient.EWSClient INFO - getAvailability()    event 3 start: Thu Mar 05 19:00:00 EST 2015 end: Thu Mar 05 22:00:00 EST 2015
```

### PR DESCRIPTION
**Pull request by cfraser**
This pull request resolves an issue where the ```TimeWindow``` can be incorrectly shifted because it is serialized to ```"yyyy-MM-dd'T'00:00:00"``` in the timezone of the server and deserialized in UTC. This occurs for two reasons:
* SimpleDateFormat uses the timezone of the system when a timezone has not been explicitly set
* the ```Date``` is serialized without a timezone value and a fixed time of 0:00:00, and then deserialized by [EwsServiceXmlReader.readElementValueAsUnbiasedDateTimeScopedToServiceTimeZone()](https://github.com/OfficeDev/ews-java-api/blob/1c8add6b1b3a0597a47d039157da5bb95226ff5a/src/main/java/microsoft/exchange/webservices/data/core/EwsServiceXmlReader.java#L90) which explicitly sets 'UTC' as the timezone.

Additionally, treating a date with no timezone as UTC also conforms to [Table 2](https://msdn.microsoft.com/en-us/library/office/dn789029(v=exchg.150).aspx#sectionSection1) in the Handling Timezones in EWS section of [Time zones and EWS in Exchange](https://msdn.microsoft.com/en-us/library/office/dn789029(v=exchg.150).aspx).

* set the timezone to UTC on the formatter in ```writeToXmlUnscopedDatesOnly```
* resolves #241

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cfraser__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by cfraser** [comment]
I'm investigating if I need legal sign-off for the CLA.

**Comment by serious6** [comment]
In my opinion the whole TimeSpan class should be replaced with [joda#period](http://joda-time.sourceforge.net/apidocs/org/joda/time/Period.html) any comments?

**Comment by cfraser** [comment]
That sounds reasonable. I try to make that conversion in another PR. 

Is that perhaps a separate concern from this PR given that ```TimeSpan``` isn't used in the ```TimeWindow``` class?

**Comment by serious6** [comment]
this PR should be referenced against the 2.0.x branch as this will be a minor change.

**Comment by cfraser** [comment]
Talked to legal, now I'm waiting on my senior director to sign then we should be good.

**Comment by cfraser** [comment]
Should I open another PR to 2.0.x once this merges into master?

**Comment by serious6** [comment]
can you also add some explanation on why we need this change in detail?

**Comment by cfraser** [comment]
I'll add it to the PR description shortly.

**Comment by cfraser** [comment]
@serious6 I've updated the PR description to explain my reasoning for the pull request. Please let me know if you need any further details, or have any concerns.

**Comment by serious6** [comment]
@cfraser cla still needs to be signed.

**Comment by cfraser** [comment]
@serious6 I've signed it and I'm waiting on my senior manager to sign. I just sent him a follow up email to try and move things along.

**Comment by azurecla** [comment]
__@cfraser__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by serious6** [comment]
@cfraser thanks for your contribution.

**Pull request merged**
