### PR TITLE
remove new ews-java-api.jar from repo

### PR DESCRIPTION
**Pull request by serious6**
it will otherwise always track uploading the cache

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@serious6__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vboctor** [comment]
:+1: for the change.  Though the "track uploading the cache" side effect is not clear to me.  If you can clarify the commit comment, that would be great.

**Comment by serious6** [comment]
ill update the commit message but only to explain what I meant:
every travis build runs `mvn install` this will have our jars assembled and then these jars will be deployed to the local travis repository (located at `$HOME/.m2/repository`) since with every mvn install these jars will change due to the changed api the complete repository will be uploaded to the cache. To prevent this we can delete the ews-java-api folder before the repository gets to cache (we will not need our own jar in the repo as well so the deletion has no side effects).

**Comment by vbauer** [comment]
:+1:

**Comment by serious6** [comment]
commit-msg is updated

**Pull request merged**
