### PR TITLE
Correction of isAssignableFrom usage inside tryGetValue

### PR DESCRIPTION
**Pull request by andrejusc**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@andrejusc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
@andrejusc thanks for your contribution. Currently the travis build is failing because of `ExtendedPropertyCollectionTest`. After a small run I noticed that the test initialises a `new ExtendedPropertyDefinition();` which will by default set mapiType as a String. This does the trick why we dont get any exception as expected. Maybe you can edit this test and add some other ones to prove  the correctness of your function.

**Comment by andrejusc** [comment]
Modified test case so it could pass again

**Comment by serious6** [comment]
@andrejusc can you please add some other test cases? positiv tests etc. for instance?

**Comment by andrejusc** [comment]
Added one positive test case now. Hope that suits at least current contribution.

**Comment by serious6** [comment]
thanks. One test is not much but better than nothing.

**Pull request merged**
