### PR TITLE
Move IFunctions in separate class

### PR DESCRIPTION
**Pull request by vbauer**
It allows to:
* remove some duplicated code
* re-use thread-safe instances of IFunction interface

I also added unit tests for this changes.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vbauer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
@vbauer please also state what makes this important.

**Comment by vbauer** [comment]
**1.** In the current approach we have a lot of unnecessary duplicated code. For example this function repeats 5-6 times and each time it takes 5 lines of code:
```java
new IFunction<Object,String>() {
  public String func(Object o) {
    return o.toString();
  }
}
```
It could be replaced by simple single line of code:
```java
IFunctions.ToString.INSTANCE
```

**2.** Anonymous functions contain unnecessary references to the outer-classes. New way clear this situation. We do not need these references - no need to use them.

**3.** It allows to prevent unnecessary mistakes, because we use only functions which are covered by unit tests.

**4.** Also it allows to prevent unnecessary creation of `IFunction` instances. It means that we spend zero time to instantiate it and we spend zero time to collect garbage.

**Comment by serious6** [comment]
@vbauer thanks for the contribution

**Comment by vbauer** [comment]
@serious6 Thanks for merge. :)

**Pull request merged**
