### PR TITLE
Removed IntelliJ files

### PR DESCRIPTION
**Pull request by vanta**
Related to #454

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vanta__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
@vanta the reason why we made the integration of the idea specific project files is that we wanted people to be enforced to use the documented formatter. From my point of view just removing the files does not resolve the conflict. Any comments?

**Comment by vanta** [comment]
@serious6 Thanks for your comment. I've got your point. I'm an IntelliJ user as well so glad to hear that but how about other IDEs' users? Formatting still can be messed up as the is no way to enforce formatting in IDE (user can always change it or don't format).

Maybe this formatting check can be one of build steps (by using some plugin)?

**Comment by serious6** [comment]
@vanta thanks for your support.

**Pull request merged**
