### PR TITLE
Building against multiple jdk

### PR DESCRIPTION
**Pull request by serious6**
As mentioned in #181 we ran into issues because there where differences in the used jdk. This PR tries to prevent this in the future by adding maven profiles for travis-ci which will now build the api against all available jdk's. This also prevents the build from failing while compiling with jdk1.8 with enabled doclint function.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@serious6__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vboctor** [comment]
Will this make it a requirement that every developer has to have all supported JDKs installed?

**Comment by serious6** [comment]
No it is just about the Travis build. Local building remains uneffected.

**Comment by evpaassen** [comment]
I think we should not use seperate build profiles for CI. The build should from CI should be reproducable by the developer. Ideally, the `pom.xml` should not know anything about CI.

Furthermore, building with JDK 1.7 or JDK 1.8 does not mean we need to adjust the Java source and target level. In fact, this should always be `1.6`.

**Comment by serious6** [comment]
hmm maybe you are right. This indicates also to add (for the programmer unused) overhead to the `pom.xml`. I will update the PR.

**Pull request merged**
