### PR TITLE
Fix parse problem in EwsUtilities

### PR DESCRIPTION
**Pull request by serious6**
fixes a parsing problem in EwsUtilities. Also includes some tests for
the parsing process as well as some additional parsing behaviors.
_ref.:_ #296, #300, #301

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@serious6__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by serious6** [comment]
thanks @tomravn for the given input on the defect.

**Comment by serious6** [comment]
maybe to make the api work again we should avoid a long delay in merging this. So any feedback is welcome.

**Comment by vboctor** [comment]
:+1:

**Pull request merged**
