### PR TITLE
Fix #276 Streaming subscription throws connection error

### LINKED ISSUE #276: StreamingSubscription - Get error: Connection is still allocated
For the following code:

WellKnownFolderName sd = WellKnownFolderName.Inbox;
			FolderId folderId = new FolderId(sd);

			List<FolderId> folder = new ArrayList<FolderId>();
			folder.add(folderId);

			StreamingSubscription subscription = service.subscribeToStreamingNotifications(folder, EventType.NewMail);
			StreamingSubscriptionConnection conn = new StreamingSubscriptionConnection(service, 30);
			conn.addSubscription(subscription);
			EventDelegate delegate = new EventDelegate(service);
			conn.addOnNotificationEvent(delegate);
			conn.addOnDisconnect(delegate);
			conn.open();
			EmailMessage msg = new EmailMessage(service);
			msg.setSubject("Testing Streaming Notification on " + new Date());
			msg.setBody(MessageBody.getMessageBodyFromText("Streaming Notification Test"));
			msg.getToRecipients().add("someone@somewhere.com");
			msg.send();

I get the following error:

microsoft.exchange.webservices.data.exception.ServiceRequestException: The request failed. Connection is still allocated
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:80)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:160)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:592)
	at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:651)
	at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:247)
	at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147)
	at microsoft.exchange.webservices.data.core.service.item.EmailMessage.send(EmailMessage.java:258)
	at test.TestEWS.main(TestEWS.java:287)
Caused by: java.lang.IllegalStateException: Connection is still allocated
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.getConnection(BasicHttpClientConnectionManager.java:248)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager$1.get(BasicHttpClientConnectionManager.java:199)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:173)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at microsoft.exchange.webservices.data.core.request.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:291)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:780)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:719)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:68)
	... 7 more

### PR DESCRIPTION
**Pull request by avromf**
Fixes issues with subscriptions (e.g. streaming) and now uses a PoolingHttpClientConnectionManager instead of BasicHttpClientConnectionManager.
Specifically, it will create a separate PoolingHttpClientConnectionManager for subscriptions while still retaining the BasicHttpClientConnectionManager for all other connections.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@avromf__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@avromf__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by serious6** [comment]
@avromf can you provide more information on the incident? Are there any existing issues corresponding to this (if not will you create one)?

**Comment by avromf** [comment]
Yes, it is in the title, issue #276.

**Comment by avromf** [comment]
In a nutshell, my fix here follows @MikeN123 's suggestion in the comments on issue #276 that a separate pooling manager should be created for subscriptions.

**Comment by MikeN123** [comment]
Please note that the `PoolingHttpClientConnectionManager` only creates 2 connections per route by default, so you can only have 2 subscriptions at the moment (I think). Maybe that should be fixed, other than that it seems like an ok workaround to me (but I did not look at the PR in detail).

A better solution would be to rewrite the complete connection handling, but that's would probably be quite some work.

**Comment by avromf** [comment]
@MikeN123 I went back and tested this by creating more than 2 subscriptions and you are correct. It hits the default limit of 2.
I also went back and took a look at the original code before the change to <code>BasicHttpClientConnectionManager</code>. It also had the same limitation.
Should we increase the limit and if so, what should we increase it to?

**Comment by MikeN123** [comment]
10 would probably be ok, with an option to change it, since that is also the default value for Exchange (`HangingConnectionLimit` setting)

**Comment by serious6** [comment]
@avromf are you planning any further changes on this?

**Comment by kentongray** [comment]
just so you guys know I just verified this appears to have fixed this problem for us

**Comment by kentongray** [comment]
i'm happy to wrap this up if @avromf is unable to at this time (he did all the hard work already).  is the only concern the connection pool?

**Comment by avromf** [comment]
I'm currently busy today and tomorrow, but I may be able to take care of it next week.
Setting the connection pool to increase the limit beyond 2 is not an issue, my only concern is @MikeN123 suggestion to have an option to change it. How is that supposed to be done? Via a method call?

**Comment by MikeN123** [comment]
A method call should be ok (and maybe an overloaded constructor for convenience?). I would also increase the defaults to 10 or something. Docs on how to set the limits can be found here: https://hc.apache.org/httpcomponents-client-4.4.x/tutorial/html/connmgmt.html#d5e393

**Comment by serious6** [comment]
Even though a number of 10 seems some kind of random to me this should be more usefull then the restricted value of 2. Once added we should also include an update to the readme/wiki to mention the possible change of the connection size.

**Comment by MikeN123** [comment]
10 was not really randomly chosen, it's the default max concurrency of EWS. But the streaming subscriptions seem to use another limit (`HangingConnectionLimit`), which seems to have a default of 3 according to https://msdn.microsoft.com/en-us/library/office/jj945066(v=exchg.150).aspx#bk_ThrottlingNotifications

**Comment by avromf** [comment]
@MikeN123 The only thing I was wondering about is that it was also suggested that the implementation be completely written. Assuming this is actually done some time in the future, that may possibly make any API changes (like the addition of a method to set the number of connections in the pool) obsolete.
Should we then simply leave it at max 10 since the chances that someone may need to change it are rare?

**Comment by MikeN123** [comment]
It's probably a small effort to add 1 method that gives the opportunity to change the maximum, so why not add it then?

**Comment by serious6** [comment]
@avromf any update on this? Are there any questions left or are you just busy?

**Comment by avromf** [comment]
No, no more questions, just currently busy.

**Comment by serious6** [comment]
@avromf maybe we should get this in shortly. If you dont have time @kentongray should support as offered.

**Comment by serious6** [comment]
@avromf this PR is now open for over 1 month. I would love to have this integrated in stable 2.0 release. So if you want your name on this change please have this PR updated and apply the wanted changes. If I dont notice any changes here within the next days I will address this issue on my own and close this PR due to lag of contribution.

**Comment by avromf** [comment]
Sorry for the delay, @serious6 . I've now set the default number of connections for the pooling manager to 10 and added a method allowing one to change it if needed.
I've also merged it with the latest. (I hope I did that correctly.)

**Comment by serious6** [comment]
@avromf thanks for the work. Unfortunately your commits also include some conflict resolution which we should not have on the upstream/master.Maybe you can reset these commits resolve the conflicts and only commit the changes made? If you are facing any trouble plz report back.

**Comment by avromf** [comment]
While in my attempt to fix this, this pull request ended up being closed thus I have created a new one.
#336

**Pull request closed without merging**
